// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi5ek4664vh3Tj-FmyuWIWcDeD81krA0Q',
    appId: '1:426613210580:web:772dc10f0ed0212ae36a41',
    messagingSenderId: '426613210580',
    projectId: 'manejatuscuentas',
    authDomain: 'manejatuscuentas.firebaseapp.com',
    storageBucket: 'manejatuscuentas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0tgrfGySNtH7oA6ZgV6FGQ6HvI5Mx-VU',
    appId: '1:426613210580:android:900d843f3c8e6ea7e36a41',
    messagingSenderId: '426613210580',
    projectId: 'manejatuscuentas',
    storageBucket: 'manejatuscuentas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRl0Eq3LdRLRi_MiwP9uCbNQSZqIaC0oY',
    appId: '1:426613210580:ios:98e9bd78c81da22fe36a41',
    messagingSenderId: '426613210580',
    projectId: 'manejatuscuentas',
    storageBucket: 'manejatuscuentas.appspot.com',
    iosClientId: '426613210580-tft0kggjopq36t5mb3ji94umtquglaiu.apps.googleusercontent.com',
    iosBundleId: 'com.nullSA.manejaTusCuentas',
  );
}
